//! Output rendering for the CLI. Three modes:
//! * `markdown(...)` — human-friendly report that mirrors
//!   `summary.md` generated by `loop_log.rs`, plus a findings section.
//! * `json(...)`     — single JSON object suitable for CI parsing.
//! * `list_tree(..)` — `project -> run-ids` tree for discovery.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

use anyhow::{Context, Result};
use aura_loop_log_schema::{RunCounters, RunMetadata};
use aura_run_heuristics::{BundleView, Finding, Severity};
use serde::Serialize;

pub fn markdown(bundle: &BundleView, findings: &[Finding], bundle_dir: &Path) -> Result<()> {
    let mut out = String::new();
    render_header(&mut out, &bundle.metadata, bundle_dir);
    render_counters_table(&mut out, &bundle.metadata.counters);
    render_findings(&mut out, findings);
    write_stdout(&out).context("writing markdown output")
}

pub fn json(bundle: &BundleView, findings: &[Finding]) -> Result<()> {
    #[derive(Serialize)]
    struct Report<'a> {
        metadata: &'a RunMetadata,
        summary: Summary,
        findings: &'a [Finding],
    }
    #[derive(Serialize)]
    struct Summary {
        error_count: usize,
        warn_count: usize,
        info_count: usize,
        total: usize,
    }

    let summary = Summary {
        error_count: count_at(findings, Severity::Error),
        warn_count: count_at(findings, Severity::Warn),
        info_count: count_at(findings, Severity::Info),
        total: findings.len(),
    };
    let report = Report {
        metadata: &bundle.metadata,
        summary,
        findings,
    };
    let payload = serde_json::to_string_pretty(&report)?;
    write_stdout(&payload).context("writing json output")?;
    write_stdout("\n").context("writing json newline")?;
    Ok(())
}

pub fn list_tree(loop_logs_dir: &Path) -> Result<()> {
    if !loop_logs_dir.is_dir() {
        write_stdout(&format!(
            "loop logs directory not found: {}\n",
            loop_logs_dir.display()
        ))
        .context("writing list placeholder")?;
        return Ok(());
    }
    let mut projects: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for entry in fs::read_dir(loop_logs_dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let mut runs = Vec::new();
        if let Ok(inner) = fs::read_dir(&path) {
            for run_entry in inner.flatten() {
                let run_path = run_entry.path();
                if !run_path.is_dir() {
                    continue;
                }
                if let Some(run_name) = run_path.file_name().and_then(|n| n.to_str()) {
                    runs.push(run_name.to_owned());
                }
            }
        }
        runs.sort();
        projects.insert(name.to_owned(), runs);
    }
    let mut out = String::new();
    let _ = writeln!(out, "# Loop logs at {}", loop_logs_dir.display());
    for (project, runs) in &projects {
        let _ = writeln!(out, "- {project}");
        for run in runs {
            let _ = writeln!(out, "  - {run}");
        }
    }
    if projects.is_empty() {
        let _ = writeln!(out, "(no projects found)");
    }
    write_stdout(&out).context("writing list tree")
}

fn render_header(out: &mut String, metadata: &RunMetadata, bundle_dir: &Path) {
    let _ = writeln!(out, "# Run {} — {:?}", metadata.run_id, metadata.status);
    let _ = writeln!(out);
    let _ = writeln!(out, "- path: `{}`", bundle_dir.display());
    let _ = writeln!(out, "- project_id: `{}`", metadata.project_id);
    let _ = writeln!(
        out,
        "- agent_instance_id: `{}`",
        metadata.agent_instance_id
    );
    let _ = writeln!(out, "- started_at: {}", metadata.started_at.to_rfc3339());
    if let Some(ended) = metadata.ended_at {
        let duration = ended.signed_duration_since(metadata.started_at);
        let _ = writeln!(out, "- ended_at: {}", ended.to_rfc3339());
        let _ = writeln!(out, "- duration: {}s", duration.num_seconds().max(0));
    }
    let _ = writeln!(out);
}

fn render_counters_table(out: &mut String, counters: &RunCounters) {
    let _ = writeln!(out, "## Counters");
    let _ = writeln!(out);
    let _ = writeln!(out, "| metric | value |");
    let _ = writeln!(out, "| --- | ---: |");
    let _ = writeln!(out, "| events_total | {} |", counters.events_total);
    let _ = writeln!(out, "| llm_calls | {} |", counters.llm_calls);
    let _ = writeln!(out, "| iterations | {} |", counters.iterations);
    let _ = writeln!(out, "| blockers | {} |", counters.blockers);
    let _ = writeln!(out, "| retries | {} |", counters.retries);
    let _ = writeln!(out, "| tool_calls | {} |", counters.tool_calls);
    let _ = writeln!(out, "| task_completed | {} |", counters.task_completed);
    let _ = writeln!(out, "| task_failed | {} |", counters.task_failed);
    let _ = writeln!(out, "| input_tokens | {} |", counters.input_tokens);
    let _ = writeln!(out, "| output_tokens | {} |", counters.output_tokens);
    let _ = writeln!(out);
}

fn render_findings(out: &mut String, findings: &[Finding]) {
    let _ = writeln!(out, "## Findings");
    let _ = writeln!(out);
    if findings.is_empty() {
        let _ = writeln!(out, "_no findings — analyzer is happy._");
        return;
    }
    for severity in [Severity::Error, Severity::Warn, Severity::Info] {
        let group: Vec<&Finding> = findings.iter().filter(|f| f.severity == severity).collect();
        if group.is_empty() {
            continue;
        }
        let _ = writeln!(
            out,
            "### {} ({})",
            severity_heading(severity),
            group.len()
        );
        let _ = writeln!(out);
        for f in group {
            let _ = writeln!(out, "- **{}** _({})_", f.title, f.id);
            let _ = writeln!(out, "  {}", f.detail);
            if let Some(tid) = f.task_id {
                let _ = writeln!(out, "  task: `{tid}`");
            }
        }
        let _ = writeln!(out);
    }
}

fn severity_heading(sev: Severity) -> &'static str {
    match sev {
        Severity::Error => "Errors",
        Severity::Warn => "Warnings",
        Severity::Info => "Info",
    }
}

fn count_at(findings: &[Finding], severity: Severity) -> usize {
    findings.iter().filter(|f| f.severity == severity).count()
}

fn write_stdout(s: &str) -> io::Result<()> {
    let stdout = io::stdout();
    let mut lock = stdout.lock();
    lock.write_all(s.as_bytes())?;
    lock.flush()
}
