import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

test("high-resolution capture stays generic and does not encode feature-specific routes", () => {
  const sourcePath = path.join(import.meta.dirname, "changelog-media-highres-capture.mjs");
  const source = fs.readFileSync(sourcePath, "utf8");

  assert.doesNotMatch(source, /GPT-5\.5|open-model-picker|model-picker|feedback-composer|agent-editor/);
  assert.match(source, /\[data-agent-surface\]/);
  assert.match(source, /\[data-agent-context\]/);
  assert.match(source, /\[data-agent-action\]/);
  assert.match(source, /width:\s*1280/);
  assert.match(source, /height:\s*720/);
  assert.match(source, /deviceScaleFactor:\s*2/);
  assert.match(source, /data-aura-changelog-capture-presentation/);
  assert.match(source, /--color-text-secondary/);
  assert.match(source, /--color-text-muted/);
  assert.match(source, /--color-border/);
  assert.match(source, /viewport-full-desktop-proof/);
  assert.match(source, /type: "png"/);
  assert.match(source, /scale: "device"/);
  assert.match(source, /animations: "disabled"/);
  assert.match(source, /caret: "hide"/);
  assert.match(source, /shouldPreferStableShellProof\(seedPlan, story\)/);
  assert.match(source, /proofIsCompactTeaser/);
  assert.doesNotMatch(source, /DEFAULT_CHANGELOG_CAPTURE_ZOOM/);
  assert.doesNotMatch(source, /DEFAULT_CHANGELOG_CAPTURE_TEXT_SCALE/);
  assert.doesNotMatch(source, /captureZoom/);
  assert.doesNotMatch(source, /captureTextScale/);
  assert.doesNotMatch(source, /data-aura-changelog-capture-zoom/);
  assert.doesNotMatch(source, /data-aura-changelog-capture-text-scale/);
  assert.doesNotMatch(source, /body\.style\.zoom/);
  assert.doesNotMatch(source, /contextCreatesMostlyEmptyFrame/);
  assert.doesNotMatch(source, /floatingProofFitsTightFrame/);
  assert.doesNotMatch(source, /expandToPresentationClip/);
  assert.doesNotMatch(source, /min-width: min\(72vw, 900px\)/);
  assert.doesNotMatch(source, /max-height: min\(68vh, 900px\)/);
  assert.doesNotMatch(source, /font-size: calc/);
  assert.doesNotMatch(source, /font-smoothing/);
  assert.doesNotMatch(source, /text-rendering/);
  assert.doesNotMatch(source, /width: calc\(.*--aura-changelog-capture-text-scale/);
});
