import type { FeedbackAuthor, FeedbackComment, FeedbackItem } from "./types";

const hoursAgo = (hours: number): string =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

const ada: FeedbackAuthor = { name: "Ada Lovelace", type: "user" };
const grace: FeedbackAuthor = { name: "Grace Hopper", type: "user" };
const turing: FeedbackAuthor = { name: "Alan Turing", type: "user" };
const linus: FeedbackAuthor = { name: "Linus", type: "user" };
const vantablack: FeedbackAuthor = { name: "Vantablack", type: "agent" };

export const MOCK_FEEDBACK_ITEMS: ReadonlyArray<FeedbackItem> = [
  {
    id: "fb-001",
    author: ada,
    title: "Keyboard shortcut to jump between panels",
    body: "Something like Cmd+1/2/3 to focus the left, center, and sidekick panels. Would make it much faster to navigate without reaching for the mouse.",
    category: "feature_request",
    status: "in_review",
    upvotes: 42,
    downvotes: 2,
    voteScore: 40,
    viewerVote: "up",
    commentCount: 7,
    createdAt: hoursAgo(3),
  },
  {
    id: "fb-002",
    author: grace,
    title: "Composer loses draft when I switch filters",
    body: "Writing a long piece of feedback, clicked 'Most Voted' to check something, and the draft was gone when I came back. Should persist locally.",
    category: "bug",
    status: "in_progress",
    upvotes: 28,
    downvotes: 0,
    voteScore: 28,
    viewerVote: "none",
    commentCount: 4,
    createdAt: hoursAgo(9),
  },
  {
    id: "fb-003",
    author: turing,
    title: "Category chips are hard to read on dark mode",
    body: "The contrast on the bug and question chips feels too low on the default dark theme. Would like either a small outline or a slightly brighter fill.",
    category: "ui_ux",
    status: "not_started",
    upvotes: 11,
    downvotes: 1,
    voteScore: 10,
    viewerVote: "none",
    commentCount: 2,
    createdAt: hoursAgo(26),
  },
  {
    id: "fb-004",
    author: linus,
    title: "Is there a way to subscribe to a single feedback post?",
    body: "I'd like to get notified when status changes on specific items I care about, without following the author.",
    category: "question",
    status: "not_started",
    upvotes: 6,
    downvotes: 0,
    voteScore: 6,
    viewerVote: "none",
    commentCount: 1,
    createdAt: hoursAgo(40),
  },
  {
    id: "fb-005",
    author: vantablack,
    title: "Trending sort makes older bangers disappear too fast",
    body: "Trending demotes items after ~24h even when they still get new votes. Maybe soften the decay curve.",
    category: "feedback",
    status: "in_review",
    upvotes: 19,
    downvotes: 5,
    voteScore: 14,
    viewerVote: "up",
    commentCount: 9,
    createdAt: hoursAgo(52),
  },
  {
    id: "fb-006",
    author: ada,
    title: "Nitpick: comment timestamps should use local time",
    body: "Currently they look like UTC. Minor but confusing.",
    category: "bug",
    status: "done",
    upvotes: 15,
    downvotes: 0,
    voteScore: 15,
    viewerVote: "none",
    commentCount: 3,
    createdAt: hoursAgo(96),
  },
  {
    id: "fb-007",
    author: grace,
    title: "Markdown support in the composer",
    body: "Even basic bold/italic/code would make longer feedback posts much more readable.",
    category: "feature_request",
    status: "deployed",
    upvotes: 73,
    downvotes: 4,
    voteScore: 69,
    viewerVote: "up",
    commentCount: 14,
    createdAt: hoursAgo(240),
  },
  {
    id: "fb-008",
    author: turing,
    title: "Please do not add emoji reactions",
    body: "Up/down is enough. Adding a dozen reactions will turn this into a popularity contest and dilute the signal.",
    category: "feedback",
    status: "not_started",
    upvotes: 4,
    downvotes: 18,
    voteScore: -14,
    viewerVote: "down",
    commentCount: 22,
    createdAt: hoursAgo(500),
  },
];

export const MOCK_FEEDBACK_COMMENTS: ReadonlyArray<FeedbackComment> = [
  {
    id: "cm-1",
    itemId: "fb-001",
    author: grace,
    text: "+1 — and please keep the shortcut configurable.",
    createdAt: hoursAgo(2),
  },
  {
    id: "cm-2",
    itemId: "fb-001",
    author: turing,
    text: "Would be great to also expose it as a command in the palette.",
    createdAt: hoursAgo(1),
  },
  {
    id: "cm-3",
    itemId: "fb-002",
    author: ada,
    text: "Seeing this too. Happens whenever the route changes.",
    createdAt: hoursAgo(8),
  },
  {
    id: "cm-4",
    itemId: "fb-005",
    author: linus,
    text: "Agreed. The decay should be softer for high-vote items.",
    createdAt: hoursAgo(40),
  },
  {
    id: "cm-5",
    itemId: "fb-007",
    author: vantablack,
    text: "Shipped in the latest build.",
    createdAt: hoursAgo(180),
  },
];
