// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStateWire } from "./ToolStateWire";

/**
 * Wire-compatible mirror of `aura_core::AgentToolPermissions`.
 */
export type AgentToolPermissionsWire = { per_tool: { [key in string]?: ToolStateWire }, };
