// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `approval_response`.
 */
export type ApprovalResponse = { tool_use_id: string, approved: boolean, };
