// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesChanged } from "./FilesChanged";
import type { SessionUsage } from "./SessionUsage";

/**
 * Payload for `assistant_message_end`.
 */
export type AssistantMessageEnd = { message_id: string, stop_reason: string, usage: SessionUsage, files_changed: FilesChanged, 
/**
 * Phase 5 billing roll-up: the originating user whose budget
 * should absorb this turn's cost. When `None`, the immediate
 * agent owner is billed (today's behavior). Populated by the
 * harness when a spawned agent's work should roll up to the
 * ancestor user via `walk_parent_chain`. Strictly additive —
 * older harness builds never set this field; older clients
 * ignore it on deserialize.
 */
originating_user_id: string | null, };
