// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A prior conversation message used to hydrate session history.
 */
export type ConversationMessage = { role: string, content: string, };
