// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of file mutations during a turn.
 */
export type FilesChanged = { created: Array<string>, modified: Array<string>, deleted: Array<string>, };
