// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `generation_progress`.
 */
export type GenerationProgressMsg = { percent: number, message: string, };
