// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `generation_partial_image`.
 */
export type GenerationPartialImage = { data: string, };
