// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Payload for `generation_completed`.
 *
 * The `payload` field carries the raw response from the generation backend,
 * whose shape varies by mode (image vs 3D).
 */
export type GenerationCompleted = { mode: string, payload: JsonValue, };
