// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledToolRuntimeProviderExecution } from "./InstalledToolRuntimeProviderExecution";

export type InstalledToolRuntimeExecution = { "type": "app_provider" } & InstalledToolRuntimeProviderExecution;
