// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledToolIntegrationRequirement } from "./InstalledToolIntegrationRequirement";
import type { InstalledToolRuntimeExecution } from "./InstalledToolRuntimeExecution";
import type { JsonValue } from "./serde_json/JsonValue";
import type { ToolAuth } from "./ToolAuth";

export type InstalledTool = { name: string, description: string, input_schema: JsonValue, endpoint: string, auth: ToolAuth, timeout_ms: bigint | null, namespace: string | null, required_integration: InstalledToolIntegrationRequirement | null, runtime_execution: InstalledToolRuntimeExecution | null, metadata: { [key in string]?: JsonValue }, };
