// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledToolRuntimeIntegration } from "./InstalledToolRuntimeIntegration";

export type InstalledToolRuntimeProviderExecution = { provider: string, base_url: string, static_headers: { [key in string]?: string }, integrations: Array<InstalledToolRuntimeIntegration>, };
