// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledToolRuntimeAuth = { "type": "none" } | { "type": "authorization_bearer", token: string, } | { "type": "authorization_raw", value: string, } | { "type": "header", name: string, value: string, } | { "type": "query_param", name: string, value: string, } | { "type": "basic", username: string, password: string, };
