// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledToolRuntimeAuth } from "./InstalledToolRuntimeAuth";
import type { JsonValue } from "./serde_json/JsonValue";

export type InstalledToolRuntimeIntegration = { integration_id: string, base_url: string | null, auth: InstalledToolRuntimeAuth, provider_config: { [key in string]?: JsonValue }, };
