// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-session model overrides applied on top of the harness's
 * env-default router config.
 *
 * All LLM traffic flows through aura-router (the AURA proxy) using a
 * per-request JWT; there is no direct-provider path, so this struct
 * only carries knobs that still mean something for proxy routing:
 * model name, fallback model, prompt-caching toggle. `None` on a field
 * means "leave the harness default unchanged".
 */
export type SessionModelOverrides = { 
/**
 * Optional default model for this session.
 */
default_model: string | null, 
/**
 * Optional fallback model used on 429/529 retries.
 */
fallback_model: string | null, 
/**
 * Optional override for whether Anthropic prompt-caching directives
 * should be attached.
 */
prompt_caching_enabled: boolean | null, };
