// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `thinking_delta`.
 */
export type ThinkingDelta = { thinking: string, };
