// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `tool_result`.
 */
export type ToolResultMsg = { name: string, result: string, is_error: boolean, tool_use_id: string | null, };
