// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-compatible tri-state tool permission value.
 *
 * Used by [`crate::AgentToolPermissionsWire`] (inbound) and
 * [`crate::ToolInfo`] (outbound) so the harness and clients can agree on
 * the effective state of a tool for a session.
 */
export type ToolStateWire = "on" | "off" | "ask";
