// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Payload for `tool_call_snapshot` -- incrementally accumulated tool input.
 */
export type ToolCallSnapshot = { id: string, name: string, input: JsonValue, };
