// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope for remembering a live tool approval decision.
 *
 * Used inbound on [`crate::ToolApprovalResponse`] and offered
 * outbound by the harness on [`crate::ToolApprovalPrompt::remember_options`].
 */
export type ToolApprovalRemember = "once" | "session" | "forever";
