// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User decision for a live tool approval prompt.
 *
 * Sent inbound on [`crate::ToolApprovalResponse`].
 */
export type ToolApprovalDecision = "on" | "off";
