// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStateWire } from "./ToolStateWire";

/**
 * Minimal tool info for the `session_ready` response.
 */
export type ToolInfo = { name: string, description: string, effective_state: ToolStateWire, };
