// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ToolApprovalRemember } from "./ToolApprovalRemember";

/**
 * Payload for `tool_approval_prompt`.
 */
export type ToolApprovalPrompt = { request_id: string, tool_name: string, args: JsonValue, agent_id: string, remember_options: Array<ToolApprovalRemember>, };
