// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication configuration for installed tools.
 */
export type ToolAuth = { "type": "none" } | { "type": "bearer", token: string, } | { "type": "api_key", header: string, key: string, } | { "type": "headers", headers: { [key in string]?: string }, };
