// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolApprovalDecision } from "./ToolApprovalDecision";
import type { ToolApprovalRemember } from "./ToolApprovalRemember";

/**
 * Payload for `tool_approval_response`.
 */
export type ToolApprovalResponse = { request_id: string, decision: ToolApprovalDecision, remember: ToolApprovalRemember, };
