pub(crate) mod channel_ext;
pub(crate) mod constants;
mod error;
mod chat;
mod chat_agent;
mod chat_context;
mod chat_message_conversion;
mod chat_persistence;
mod chat_sanitize;
mod chat_streaming;
mod chat_tool_executor;
mod chat_tool_handlers;
mod chat_tool_loop_executor;
pub mod compaction;
pub mod message_metadata;
mod tool_loop_types;
mod tool_loop_blocking;
mod tool_loop_budget;
mod tool_loop_read_guard;
mod tool_loop_streaming;
pub mod tool_loop;

pub use error::ChatError;
pub use chat::{ChatAttachment, ChatService, ChatStreamEvent};
pub use chat_tool_executor::{ChatToolExecutor, ToolExecResult};
pub use message_metadata::{encode_message_content, decode_message_content, DecodedMessage};
pub use tool_loop::{run_tool_loop, AutoBuildResult, BuildBaseline, ToolCallResult, ToolExecutor, ToolLoopConfig, ToolLoopEvent, ToolLoopResult};
